server:
  port: 8082

spring:
  application:
    name: permission-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.127.102:8848
        namespace: public
        group: DEFAULT_GROUP
        metadata:
          version: 1.0.0
          management.context-path: /actuator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_permission?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# Seata 分布式事务配置（整合后的完整配置）
seata:
  application-id: permission-service
  tx-service-group: permission-service-group
  # 注册中心配置
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.127.102:8848
      group: DEFAULT_GROUP
      namespace: public
      cluster: default
      username: "nacos"
      password: "nacos"
      context-path: ""
  # 配置中心配置
  config:
    type: nacos
    nacos:
      server-addr: 192.168.127.102:8848
      namespace: public
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
      data-id: seataServer.properties

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml

# 日志配置
logging:
  level:
    com.ajiang.permissionservice: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always