server:
  port: 8083

spring:
  application:
    name: logging-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.127.102:8848
        namespace: public
        group: DEFAULT_GROUP
        metadata:
          version: 1.0.0
          management.context-path: /actuator
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_log?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5

  # RabbitMQ 消费者配置
  rabbitmq:
    host: 192.168.127.102
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual  # 改为手动确认模式
        concurrency: 5
        max-concurrency: 20
        prefetch: 10
        # 禁用Spring Boot自带的重试机制，使用自定义重试逻辑
        retry:
          enabled: false
          max-attempts: 1

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/ajiang/loggingservice/mapper/xml/*.xml
  type-aliases-package: com.ajiang.loggingservice.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    com.ajiang.loggingservice: debug
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
  file:
    name: logs/logging-service.log
    max-size: 10MB
    max-history: 30

# 监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always